services:
  api:
    image: webcoos-object-detection:latest
    build:
      context:      .
      dockerfile:   Dockerfile
    ports:
     - 8000:8000
    tmpfs:
     - "/outputs"
    environment:
     - OUTPUT_DIRECTORY=/outputs
     - AUTHORIZED_BEARER_TOKENS
    command: >
      gunicorn api:app
        --bind "0.0.0.0:8000"
        --timeout 240
        -w 1 --max-requests 100
        -k uvicorn.workers.UvicornWorker
