name: webcoos_object_detection
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.9,<3.13
  # API-related
  - fastapi
  - gunicorn
  - python-multipart
  - uvicorn
  - filetype
  - prometheus_client
  # Model/ML-related
  - numpy
  - opencv
  # ultralytics dependencies
  - ultralytics
  - pytorch>=1.8
  - torchvision
  # For managing large git files
  - git-lfs
  # Testing related
  - flake8>=3.7.9
