name: webcoos_object_detection
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.9,<3.13
  # API-related
  - fastapi
  - gunicorn
  - python-multipart
  - uvicorn
  - filetype
  - prometheus_client
  # Model/ML-related
  - numpy
  - opencv
  # sahi dependencies
  - sahi
  # For managing large git files
  - git-lfs
  # Testing related
  - flake8>=3.7.9
  # pip
  - pip
  - pip:
    - torch==2.5.1, --index-url https://download.pytorch.org/whl/cu115
    - torchvision --index-url https://download.pytorch.org/whl/cu115
    - ultralytics
